### ISSUE TITLE
More relaxed license

### ISSUE THREAD

**Issue by andvgal** [DexPatcher/multidexlib2#11]
Hi @Lanchon 

Would you please consider releasing the library with more relaxed license, like LGPLv3 or even Apache-2?

Unfortunately, GPLv3 seriously limits usage of your work.

Thanks

**Comment by Lanchon** [comment]
hi,

thanks for getting in touch.

> GPLv3 seriously limits usage of your work.

it is a two way street. i could argue that your license, whatever that may be, limits the usefulness of YOUR work, including loosing compatibility with all GPL code.

i believe that all free software should be GPL and that publishing under more permissive licenses darkens the future landscape of software for all humanity (though sometimes it is worth doing it to attain a crucial but short term goal).

GPL avoids blatant misuse of code even against their "owners", meaning the people as large, as you can clearly see happening for example in the proprietarization of the android platform by google, which does untold harm to the world. each piece of code published under permissive licenses empowers the wrong people while doing nothing for the right people.

i will publish under the same license as smali/dexlib2 if you can show me how that would benefit the public at large.

but i will not just for the sake of being used by more projects.

i understand this is mostly a no answer. sorry for that. thanks again.

**Comment by andvgal** [comment]
Dude, as an author of a large derived GPLv3 work, I can tell how it is easily used for bad, how the license is violated and used also [against the author with a large damage](https://medium.com/@andvgal/cryptocurrency-of-the-3rd-generation-lessons-learned-2f36d18587f). You you can easily notice, that I do lots of open source (e.g. [futoin](https://github.com/futoin/), [codingfuture](https://github.com/codingfuture/)) with quite permissive Apache-2 license. And finally, but not last, I can tell something about doing [better for this World](https://github.com/krps/law).

It's not black&white. By creating a permissive license, you can help your contribution to this World to widespread also in commercial software. The reality is that unless it is used for commercial projects, the major real-world use case remains in software cracking for phishing attacks with billions in damages done to innocent users.
